version: "3.2"

services:
  ghost:
    image: ghost:alpine
    container_name: ghost
    restart: always
    ports:
      - 8080:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: $DB_PASSWORD
      database__connection__database: ghost
      url: http://richter.pm
    volumes:
      - ./content:/var/lib/ghost/content
    depends_on:
      - db
  db:
    image: yobasystems/alpine-mariadb:arm32v7
    container_name: ghost_db
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - mysql-data:/var/lib/mysql

# Use a docker managed volume for data persistency across reboots
volumes:
  mysql-data:
